export const allProjects = [
  {
    id: 1,
    categore: ["css"],
    image: "/img/hc1.png",
    title: "Restoran",
    desc: "Website Restaurant build with HTML,CSS This website is Responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/restaurant-with-anemation/",
    github: "https://github.com/Mohammed-Omar-2003/restaurant-with-anemation",
  },
  {
    id: 2,
    categore: ["css"],
    image: "/img/hc2.png",
    title: "Template CSS",
    desc: "Website A site to apply many tools within CSS, such as animation and so on. The site is responsive to all screens. build use HTML,CSS This website is Responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/Applied-CSS/",
    github: "https://github.com/Mohammed-Omar-2003/Applied-CSS",
  },
  {
    id: 3,
    categore: ["css"],
    image: "/img/hc3.png",
    title: "Power GYM",
    desc: "Power GYM is a wibsite build with HTML and CSS the website is responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/GYM/",
    github: "https://github.com/Mohammed-Omar-2003/GYM",
  },
  {
    id: 4,
    categore: ["bootstrap"],
    image: "/img/bs1.png",
    title: "Bondi",
    desc: "Bondi Website build with HTML,CSS and Bootstarp the website is responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/Bondi/",
    github: "https://github.com/Mohammed-Omar-2003/Bondi",
  },
  {
    id: 5,
    categore: ["bootstrap", "js"],
    image: "/img/jsBs1.png",
    title: "Special Design",
    desc: "Website build HTML,CSS,JS,Bootstrap,DOM and Bom the website is responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/template-js/",
    github: "https://github.com/Mohammed-Omar-2003/Bondi",
  },
  {
    id: 6,
    categore: ["bootstrap", "js"],
    image: "/img/jsBs2.png",
    title: " Clothes Shop ",
    desc: "Ecommerce Website shop build HTML,CSS,JS,Bootstrap,DOM and Bom the website is responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/Ecommerce/",
    github: "https://github.com/Mohammed-Omar-2003/Ecommerce",
  },
  {
    id: 7,
    categore: ["js"],
    image: "/img/js1.png",
    title: "Calculator",
    desc: "Simple Calculator build HTML,CSS and JS the website is responsive in all screen  ",
    link: "https://mohammed-omar-2003.github.io/calculator/",
    github: "https://github.com/Mohammed-Omar-2003/calculator",
  },
  {
    id: 8,
    categore: ["js"],
    image: "/img/js2.png",
    title: "CRUDS",
    desc: "Product Management System build HTML,CSS and JS the website is responsive in all screen",
    link: "https://mohammed-omar-2003.github.io/CURD/",
    github: "https://github.com/Mohammed-Omar-2003/CURD",
  },
  {
    id: 9,
    categore: ["react"],
    image: "/img/react1.png",
    title: "Restaurant",
    desc: "Ecommerce Restaurant Website build with React ,ReactBoostarp the website is responsive in all screen",
    link: "https://ecomarce-project-1e577.web.app/",
    github: "https://github.com/Mohammed-Omar-2003/EcommerceRestaurant",
  },
  {
    id: 10,
    categore: ["react"],
    image: "/img/react2.png",
    title: "Dashbord",
    desc: "Dashbord Website Build With React ,MUI,React Router Dom the website is responsive in all screen",
    link: "https://dashbord-project-b89e3.web.app/",
    github: "https://github.com/Mohammed-Omar-2003/Dashbourd-project",
  },
  {
    id: 11,
    categore: ["react"],
    image: "/img/react7.png",
    title: "Simple Cart",
    desc: "Simple Ecomerce Cart build with react , bootstrab and reduxtoolkit the website is responsive in all screen",
    link: "https://simplecart-67366.web.app/ ",
    github: "https://github.com/Mohammed-Omar-2003/simple_cart",
  },
  {
    id: 12,
    categore: ["react"],
    image: "/img/react3.png",
    title: "Zakarne",
    desc: " A site that contains many services such as supplications, an electronic rosary, determining the direction of prayer, and knowing the prayer times .",
    link: "https://zakarne-72f8b.web.app/",
    github: "https://github.com/Mohammed-Omar-2003/azkar",
  },
  {
    id: 13,
    categore: ["react"],
    image: "/img/react4.png",
    title: "My Portfolio",
    desc: "My Portfolio contant  full my works Build With React ,React Bootstrap the website is responsive in all screen",
    link: "https://portfolio-360ed.web.app/",
    github: "لسه هرفعه على الجيت",
  },
  {
    id: 14,
    categore: ["react"],
    image: "/img/react5.png",
    title: "Prayers Times",
    desc: "Prayers Times website build React and Used API the website is responsive in all screen",
    link: " https://mohammed-omar-2003.github.io/prayers-times/",
    github: "https://github.com/Mohammed-Omar-2003/prayers-times",
  },
  {
    id: 15,
    categore: ["react"],
    image: "/img/react6.png",
    title: "Weather Project",
    desc: "Weather Project website build React and Used API the website is responsive in all screen",
    link: " https://mohammed-omar-2003.github.io/weather-project/",
    github: "https://github.com/Mohammed-Omar-2003/weather-project",
  },
];
